app: '1517-develop'
ssh_url: 1517-develop@deploy.us1.frbit.com
ssh_path: null
git_remote: 1517-develop/master
before:
    code/up:
        - 'echo  "Script example: " $(git rev-parse HEAD)'
after:
    code/down:
        - 'php craft migrate/all'
