dateModified: 1552967416
email:
  fromEmail: accounts@wearetelegraph.com
  fromName: '1517'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  be195220-984a-4496-a3ec-b2db4bf7dbe2:
    name: Common
plugins:
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
siteGroups:
  f89694aa-dd36-4e72-9426-761baa648fa7:
    name: '1517'
sites:
  fb77e84e-92df-43ef-bf13-af2fe58f56fe:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: '1517'
    primary: true
    siteGroup: f89694aa-dd36-4e72-9426-761baa648fa7
    sortOrder: 1
system:
  edition: solo
  name: '1517'
  live: true
  schemaVersion: 3.1.25
  timeZone: America/Los_Angeles
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
